### ISSUE TITLE
Can this code work with big knowledge graphs with more than 1,000 nodes?

### ISSUE THREAD

**Issue by minhnguyen98** [syxu828/Crosslingula-KG-Matching#14]
When I run this code on tensorflow with big knowledge graph I get this exception:

Traceback (most recent call last):
  File "/content/gdrive/My Drive/Crosslingula-KG-Matching/run_model.py", line 405, in <module>
    main()
  File "/content/gdrive/My Drive/Crosslingula-KG-Matching/run_model.py", line 131, in main
    train_loss = train_step(g1_v_batch, g2_v_batch, label_v_batch, if_pred_on_dev=False)
  File "/content/gdrive/My Drive/Crosslingula-KG-Matching/run_model.py", line 99, in train_step
    watch, _, loss = model.act(sess, "train", dict, if_pred_on_dev)
  File "/content/gdrive/My Drive/Crosslingula-KG-Matching/model.py", line 620, in act
    results = sess.run(output_feeds, feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[32,7364,1105,400] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node node_level_matching/match_graph_1_with_graph_2/Mul (defined at content/gdrive/My Drive/Crosslingula-KG-Matching/graph_match_utils.py:10) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[aggregation_layer/second_gcn/embedding_lookup/Identity/_839]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[32,7364,1105,400] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node node_level_matching/match_graph_1_with_graph_2/Mul (defined at content/gdrive/My Drive/Crosslingula-KG-Matching/graph_match_utils.py:10) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by minhnguyen98** [comment]
I had reduced graph sized and it worked.
